# Generated by Django 4.2.4 on 2023-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('city', models.CharField()),
                ('price_min', models.PositiveIntegerField()),
                ('price_max', models.PositiveIntegerField()),
                ('room_types', models.CharField(choices=[('Entire home/apt', 'entire'), ('Private room', 'room')])),
                ('min_bedrooms', models.PositiveIntegerField()),
                ('min_beds', models.PositiveIntegerField()),
                ('date_picker_type', models.CharField(choices=[('flexible_dates', 'flexible'), ('monthly_stay', 'monthly'), ('calendar', 'calendar')])),
                ('monthly_start_date', models.DateField()),
                ('monthly_length', models.IntegerField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('flexible_trip_dates', models.JSONField()),
                ('flexible_trip_lengths', models.CharField(choices=[('one_month', 'months'), ('one_week', 'weeks'), ('weekend_trip', 'weekend')])),
            ],
        ),
    ]
