# Generated by Django 4.2.4 on 2023-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_picker_type',
            field=models.CharField(choices=[('flexible_dates', 'flexible'), ('monthly_stay', 'monthly'), ('calendar', 'calendar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='flexible_trip_lengths',
            field=models.CharField(choices=[('one_month', 'months'), ('one_week', 'weeks'), ('weekend_trip', 'weekend')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='room_types',
            field=models.CharField(choices=[('Entire home/apt', 'entire'), ('Private room', 'room')], max_length=100),
        ),
    ]
