# Generated by Django 4.2.4 on 2023-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_city_alter_task_date_picker_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='flexible_trip_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='flexible_trip_lengths',
            field=models.CharField(blank=True, choices=[('one_month', 'months'), ('one_week', 'weeks'), ('weekend_trip', 'weekend')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='monthly_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='monthly_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
