# Generated by Django 4.2.4 on 2023-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_alter_task_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='flexible_trip_dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
