# Generated by Django 4.2.4 on 2023-09-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_flexible_trip_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='city',
            new_name='query',
        ),
    ]
