# Generated by Django 4.2.4 on 2023-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_city_task_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='flexible_trip_lengths',
            field=models.CharField(blank=True, choices=[('one_month,', 'months'), ('one_week,', 'weeks'), ('weekend_trip,', 'weekend')], max_length=100, null=True),
        ),
    ]
