# Generated by Django 4.2.4 on 2023-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_flexible_trip_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomsToTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('updated', models.BooleanField(default=False)),
                ('room', models.ManyToManyField(related_name='tasks', to='tasks.room')),
                ('task', models.ManyToManyField(related_name='rooms', to='tasks.task')),
            ],
        ),
    ]
