# Generated by Django 4.2.4 on 2023-09-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_room_task_updated_roomstotasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rooms',
            field=models.ManyToManyField(through='tasks.RoomsToTasks', to='tasks.room'),
        ),
        migrations.RemoveField(
            model_name='roomstotasks',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomstotasks',
            name='task',
        ),
        migrations.AddField(
            model_name='roomstotasks',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomstotasks',
            name='task',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
    ]
