# Generated by Django 4.2.4 on 2023-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_rooms_remove_roomstotasks_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
