# Generated by Django 4.2.4 on 2023-09-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_room_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomstotasks',
            unique_together={('room', 'task')},
        ),
    ]
