apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airbot.fullname" . }}
  labels:
    	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "airbot.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.envVars}}
          env:
            {{- range .Values.envVars }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                    name: {{ include "airbot.fullname" $ }}-configmap
                    key: {{ .key }}
                    {{- end}}
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "airbot.fullname" $ }}-configmap
                  key: csrf-origins
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "airbot.fullname" $ }}-configmap
                  key: allowed-hosts
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "airbot.fullname" $ }}-configmap
                  key: postgres-host
          {{- end}}
            {{- range .Values.secretVars }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "airbot.fullname" $ }}-secret
                  key: {{ .key }}
                    {{- end}}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
