{{- if .Values.secretVars}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airbot.fullname" . -}}-secret
type: Opaque
data:
  {{- range .Values.secretVars}}
  {{ .key }}: {{ .value  | b64enc | quote }}
  {{- end}}
{{- end}}
