apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbot.fullname" . }}-service
  labels:
    {{- include "airbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
