version: '3.11'

services:
 db:
  image: postgres:13.0-alpine
  volumes:
   - postgres_db:/var/lib/postgresql/data/
  env_file:
    - .env
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]

 scraper:
  image: lordot/airscraper
  build:
   context: ../airscraper
   dockerfile: ../airscraper/Dockerfile
  restart: always
  ports:
   - "8000:8000"

 django:
  image: lordot/airbot
  build:
   context: ../airbot
   dockerfile: ../airbot/Dockerfile
  restart: always
  env_file:
   - .env
  volumes:
   - static_value:/app/static/
  depends_on:
   db:
    condition: service_healthy

 nginx:
  image: nginx:1.21.3-alpine
  ports:
   - "80:80"
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   - static_value:/var/html/static/
  depends_on:
   - django

volumes:
 static_value:
 postgres_db:
