version: '3.11'

services:
 db:
  image: postgres:13.0-alpine
  volumes:
   - postgres_db:/var/lib/postgresql/data/
  env_file:
    - .env
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]

 scraper:
  image: "${REPO}/airscraper:1.0"
  restart: always
  ports:
   - "8000:8000"

 django:
  image: "${REPO}/airbot:${TAG}"
  restart: always
  env_file:
   - .env
  volumes:
   - static_value:/app/static/
  depends_on:
   db:
    condition: service_healthy

 nginx:
  image: "{REPO}/airnginx:${TAG}"
  ports:
   - "80:80"
  volumes:
   - static_value:/var/html/static/
  depends_on:
   - django

volumes:
 static_value:
 postgres_db:
