apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress-rule.fullname" . }}
  labels:
    	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
spec:
  ingressClassName: {{ .Values.className }}
  rules:
    - http:
        paths:
          {{- with .Values.paths }}
          {{- toYaml . | nindent 8 }}
          {{- end }}