# Default values for airbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "airbot"
containerPort: 8000
probePath: "/admin"

podLabels: {app: airbot}

persistent:
  name: static-pvc
  storage: 1Gi

service:
  port: 80

volumes:
  - name: static
    persistentVolumeClaim:
      claimName: static-pvc

volumeMounts:
  - mountPath: "/app/static/"
    name: static